<a href="https://colab.research.google.com/github/shreyasjoshinie/DEVOPSLAB2/blob/main/4NI25CS187_EXP_01.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd

print("The verison of numpy",np.__version__)
print("The verison of pandas",pd.__version__)

The verison of numpy 2.0.2
The verison of pandas 2.2.3

In [ ]:
marks = np.array([78,85,92,67,88])
print("Marks:",marks)
print("type:",type(marks))
print(marks.size)

Marks: [78 85 92 67 88]
type: <class 'numpy.ndarray'>
5

In [ ]:
print("Original:",marks)
print("Add 5:",marks + 5)
print("Multiply by 2:",marks*2)
print("Divide by 2:",marks/2)
print("Sqaure:",marks**2)

Original: [78 85 92 67 88]
Add 5: [83 90 97 72 93]
Multiply by 2: [156 170 184 134 176]
Divide by 2: [39.  42.5 46.  33.5 44. ]
Sqaure: [6084 7225 8464 4489 7744]

In [ ]:
print("Sum:",marks.sum())
print("Mean:",marks.mean())
print("Maximum:",marks.max())
print("Minimum:",marks.min())

Sum: 410
Mean: 82.0
Maximum: 92
Minimum: 67

In [ ]:
print("First marks:",marks[0])
print("Second marks:",marks[1])
print("Last marks:",marks[-1])

First marks: 78
Second marks: 85
Last marks: 88

In [ ]:
print("Index 1 to 3:",marks[1:4])
print("First three",marks[:3])
print("From index 2:",marks[2:])
print("Every second element:",marks[::2])

Index 1 to 3: [85 92 67]
First three [78 85 92]
From index 2: [92 67 88]
Every second element: [78 92 88]

In [ ]:
student_marks=np.array([[78,85,92],[67,88,76],[90,95,89]])
print(student_marks)
print("Shape:",student_marks.shape)

[[78 85 92]
 [67 88 76]
 [90 95 89]]
Shape: (3, 3)

In [ ]:
print("mean of all values:",student_marks.mean())
print("Column-wise mean:",student_marks.mean(axis=0))
print("Row-wise mean:",student_marks.mean(axis=1))

mean of all values: 84.44444444444444
Column-wise mean: [78.33333333 89.33333333 85.66666667]
Row-wise mean: [85.         77.         91.33333333]

In [ ]:
data={
    "Name":["Annu","Rahul","Kiran","Priya"],
    "Branch":["CSE","AIML","CSE","AIML"],
    "Marks": [85,91,76,88]
}
df=pd.DataFrame(data)
df

    Name Branch  Marks
0   Annu    CSE     85
1  Rahul   AIML     91
2  Kiran    CSE     76
3  Priya   AIML     88

In [ ]:
print("Shape",df.shape)
print("\nColumns:")
print(df.columns)

Shape (4, 3)

Columns:
Index(['Name', 'Branch', 'Marks'], dtype='object')

In [ ]:
df.head()

    Name Branch  Marks
0   Annu    CSE     85
1  Rahul   AIML     91
2  Kiran    CSE     76
3  Priya   AIML     88

In [ ]:
df.tail()

    Name Branch  Marks
0   Annu    CSE     85
1  Rahul   AIML     91
2  Kiran    CSE     76
3  Priya   AIML     88

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    4 non-null      object
 1   Branch  4 non-null      object
 2   Marks   4 non-null      int64
dtypes: int64(1), object(2)
memory usage: 228.0+ bytes

In [ ]:
df.describe()

           Marks
count   4.000000
mean   85.000000
std     6.480741
min    76.000000
25%    82.750000
50%    86.500000
75%    88.750000
max    91.000000

In [ ]:
print("Marks Column:")
print(df["Marks"])
print("\nBranch and Marks:")
print(df[["Branch","Marks"]])

Marks Column:
0    85
1    91
2    76
3    88
Name: Marks, dtype: int64

Branch and Marks:
  Branch  Marks
0    CSE     85
1   AIML     91
2    CSE     76
3   AIML     88

In [ ]:
print("First row:")
print(df.iloc[0])
print("\nSecond row:")
print(df.iloc[1])
print("\nFirst three rows:")
print(df.iloc[:3])

First row:
Name      Annu
Branch     CSE
Marks       85
Name: 0, dtype: object

Second row:
Name      Rahul
Branch     AIML
Marks        91
Name: 1, dtype: object

First three rows:
    Name Branch  Marks
0   Annu    CSE     85
1  Rahul   AIML     91
2  Kiran    CSE     76

In [ ]:
print("First three rows:")
display(df.iloc[0:3])
print("Rows with index 1 and 3, Name and Marks:")
display(df.iloc[1:4,0:3])

First three rows:

    Name Branch  Marks
0   Annu    CSE     85
1  Rahul   AIML     91
2  Kiran    CSE     76

Rows with index 1 and 3, Name and Marks:

    Name Branch  Marks
1  Rahul   AIML     91
2  Kiran    CSE     76
3  Priya   AIML     88

In [ ]:
high_scores=df[df["Marks"]>90]
high_scores

    Name Branch  Marks
1  Rahul   AIML     91

In [ ]:
print("Students are from CSE:")
display(df[df["Branch"]=="CSE"])
print("Students scoring 85 or above:")
display(df[df["Marks"]>=85])

Students are from CSE:

    Name Branch  Marks
0   Annu    CSE     85
2  Kiran    CSE     76

Students scoring 85 or above:

    Name Branch  Marks
0   Annu    CSE     85
1  Rahul   AIML     91
3  Priya   AIML     88

In [ ]:
data={
    "Name":["Annu","Bharat","Chetan","Divya","Esha"],
    "Branch":["CSE","ISE","CSE","AIML","ISE"],
    "Marks": [72,91,84,95,68],
    "Attendance":[82,94,88,96,79]
}
students =pd.DataFrame(data)
students

     Name Branch  Marks  Attendance
0    Annu    CSE     72          82
1  Bharat    ISE     91          94
2  Chetan    CSE     84          88
3   Divya   AIML     95          96
4    Esha    ISE     68          79

In [ ]:
'''Display only name and marks'''
print("name and marks:")
display(students[["Name","Marks"]])

name and marks:

     Name  Marks
0    Annu     72
1  Bharat     91
2  Chetan     84
3   Divya     95
4    Esha     68

In [ ]:
print("Students with marks more than 80")
print(students[students["Marks"]>80])

    Name Branch  Marks
0   Annu    CSE     85
1  Rahul   AIML     91
3  Priya   AIML     88

In [ ]:
print("Students with attendace more than 85")
print(students[students["Attendance"]>=85])

Students with attendace more than 85
     Name Branch  Marks  Attendance
1  Bharat    ISE     91          94
2  Chetan    CSE     84          88
3   Divya   AIML     95          96

In [ ]:
display(students[0:3])

     Name Branch  Marks  Attendance
0    Annu    CSE     72          82
1  Bharat    ISE     91          94
2  Chetan    CSE     84          88

In [ ]:
print("Avg marks of students")
print(students["Marks"].mean())

82.0

In [ ]:
print("Maximum marks of students")
print(students["Marks"].max())

Maximum marks of students
95

In [ ]:
print("Students only from cse branch:")
print(students[students["Branch"]=="CSE"])

Students only from cse branch:
     Name Branch  Marks  Attendance
0    Annu    CSE     72          82
2  Chetan    CSE     84          88

In [ ]:
print("Students with marks above 80 and attendance above 85:")
display(students[(students["Marks"]>=80) &
            (students["Attendance"]>=85 )] )

Students with marks above 80 and attendance above 85:

     Name Branch  Marks  Attendance
1  Bharat    ISE     91          94
2  Chetan    CSE     84          88
3   Divya   AIML     95          96